int  _putchar ( char c);
int  _isupper ( int c);
 entier _isdigit ( entier c );
int  mul ( int a, int b);
void  print_numbers ( void );
void  print_most_numbers ( void );
void  more_numbers ( void );
void  print_line ( int n);
void  print_diagonal ( int n);
void  print_square ( taille int );
void  print_triangle ( taille int );
